### ISSUE TITLE
Converting to a 3D file format

### ISSUE THREAD

**Issue by unlugi** [tudelft3d/Random3Dcity#7]
Hello, 

Thank you for this tool.
I cannot view .gml .xml files generated by the two scripts.

I want to convert either the .xml or .gml to .obj. To view easily.
Could you please direct me in the right direction?
Thanks!

**Comment by fbiljecki** [comment]
Thanks for your interest. The development of this project has ceased years ago, so I am afraid extensive support cannot be provided anymore. In brief, the main output of this tool are only CityGML files (the other, XML file that is produced is for another, internal purpose of this tool). They are viewable directly in some viewers such as azul, FME, and FZK Viewer. The CityGML files have to be converted into OBJ using some other tool, such as CityGML2OBJs (https://github.com/tudelft3d/CityGML2OBJs), another development of mine that is not continued anymore due to lack of time and completion of the project. If this particular tool doesn't yield success, there are options such as FME that can be used to perform the conversion from CityGML to OBJ.

**Comment by hugoledoux** [comment]
But I would suggest you convert your files to CityJSON with this tutorial: https://www.cityjson.org/tutorials/conversion/

then you can easily convert to OBJ or others, with https://github.com/cityjson/cjio
